[pytest]
addopts = -ra -s -v --html=reports/report.html --self-contained-html
render_collapsed = none
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke tests
    checkpoint: checkpoint launch tests
